### ISSUE TITLE
[SUBMISSION] Real time, cross platform visualizations with zero dependencies for the N-body package REBOUND

### ISSUE THREAD

**Issue by hannorein** [journalovi/jovi-submissions#2]
### Title

Real time, cross platform visualizations with zero dependencies for the N-body package REBOUND

### Required sections

- [X] Abstract
- [X] A navigational aid, such as a table of contents, links or buttons between sections, or an option to switch between paper-mode and interactive mode (for more interactive/experimental articles). Some articles (e.g,. narrative visualization) might lend themselves to be progressively disclosed without an overview.
- [X] Research materials
- [X] Authorship statement (leave a placeholder if submitting anonymously)
- [X] License (CC-BY or CC-BY-SA).
- [X] Conflicts of Interest

### Desired URL stub

2024-rein-rebound

### Technical checklist

- [X] The `<title>` tag of my page contains the title of my article
- [X] The article contains an infobox indicating it is under review at JoVI
- [X] I have replaced `20XX-REPO-NAME` in the links in the infobox with my desired URL stub.

### Source repository URL

https://github.com/hannorein/jovi-rebound

### Github Pages setup

- [X] I have set up Github Pages

### Live paper URL

https://hannorein.github.io/jovi-rebound/

### Article format

Quarto

### Authors

Hanno Rein, hanno.rein@utoronto.ca, University of Toronto

### Github IDs

hannorein

### Conflicts

N/A

**Comment by mjskay** [comment]
Thanks --- this submission has been imported.

- repo: https://github.com/journalovi/2024-rein-rebound/
- live article: https://www.journalovi.org/2024-rein-rebound/
- review process: https://github.com/journalovi/2024-rein-rebound/issues

The paper is also now listed as "under review" on JoVI here: https://www.journalovi.org/under-review.html
