### ISSUE TITLE
[SUBMISSION] GLaDOS: Graph Layout algorithm Datasets for Open Science

### ISSUE THREAD

**Issue by picorana** [journalovi/jovi-submissions#4]
### Title

GLaDOS: Graph Layout algorithm Datasets for Open Science

### Required sections

- [X] Abstract
- [X] A navigational aid, such as a table of contents, links or buttons between sections, or an option to switch between paper-mode and interactive mode (for more interactive/experimental articles). Some articles (e.g,. narrative visualization) might lend themselves to be progressively disclosed without an overview.
- [X] Research materials
- [X] Authorship statement (leave a placeholder if submitting anonymously)
- [X] License (CC-BY or CC-BY-SA).
- [X] Conflicts of Interest

### Desired URL stub

2024-dibartolomeo-gd-benchmark

### Technical checklist

- [X] The `<title>` tag of my page contains the title of my article
- [X] The article contains an infobox indicating it is under review at JoVI
- [X] I have replaced `20XX-REPO-NAME` in the links in the infobox with my desired URL stub.

### Source repository URL

https://github.com/VisDunneRight/jovi-benchmark-sets

### Github Pages setup

- [X] I have set up Github Pages

### Live paper URL

https://visdunneright.github.io/jovi-benchmark-sets/

### Article format

Quarto

### Authors

Sara Di Bartolomeo, dibartolomeo.sara@gmail.com, University of Konstanz and TU Wien
Connor Wilson, wilson.conn@northeastern.edu, Northeastern University
Eduardo Puerta, puerta.e@northeastern.edu, Northeastern University
Tarik Crnovrsanin, t.crnovrsanin@northeastern.edu, Northeastern University
Alexander Frings, alexander.frings@uni-konstanz.de, University of Konstanz
Cody Dunne, c.dunne@northeastern.edu, Northeastern University

### Github IDs

picorana
codydunne
GitNax
epuer18
cwilson22
Turokhunter

### Conflicts

Organizers:
- Lonni Besançon

Associate editors:
- Andrew McNutt
- Lace Padilla

In general, anyone from our institutions (Northeastern, University of Konstanz, TU Wien) should be considered a conflict.

**Comment by floe** [comment]
Dear colleagues, thank you for your submission! We will be getting back to you ASAP. /cc @mjskay @chatchavan @lonnibesancon

**Comment by chatchavan** [comment]
Setup the JoVI Repo at https://github.com/journalovi/2024-dibartolomeo-benchmark

I've contacted the authors for the next steps.
